name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # specify your Node.js version

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test
        env:
          CI: true # Ensure the tests run in continuous integration mode

      - name: Build
        run: npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          # Your deploy script here
          echo "Deploying application..."
