name: CI/CD Pipeline

# Trigger the workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Use the Node.js version you prefer

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U testuser -d testdb; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      # Step 5: Run tests and collect coverage (assuming you have a test command in package.json)
      - name: Run tests
        run: npm test
        env:
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
          DATABASE_USER: testuser
          DATABASE_PASSWORD: testpassword
          DATABASE_NAME: testdb
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      # Step 6: Generate code coverage report
      - name: Generate code coverage
        run: npm run coverage # Update this based on your coverage script in package.json

      # Step 7: Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Make sure you added CODECOV_TOKEN as a secret in GitHub
          files: ./coverage/lcov.info # Adjust this based on where your coverage report is located
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true # Will fail the CI if Codecov cannot upload
